name: oneup
description: "Point management"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  json_annotation: '^4.9.0'
  freezed_annotation: 3.0.0
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: 3.0.6
  lints: 6.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
