openapi: 3.0.0
info:
  title: OneUp API
  description: API contract for the OneUp project.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /actions:
    post:
      summary: Create a new action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Sample Action"
      responses:
        '201':
          description: Action created successfully
    get:
      summary: Get all actions
      responses:
        '200':
          description: List of actions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123"
                    name:
                      type: string
                      example: "Sample Action"
  /actions/{id}:
    get:
      summary: Get specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      responses:
        '200':
          description: Action details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  name:
                    type: string
                    example: "Sample Action"
    put:
      summary: Update specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Action"
      responses:
        '200':
          description: Action updated successfully
    delete:
      summary: Delete specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      responses:
        '204':
          description: Action deleted successfully
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                handle:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  token_type:
                    type: string
                    example: "Bearer"
  /categories:
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Sample Category"
      responses:
        '201':
          description: Category created successfully
    get:
      summary: Get all categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123"
                    name:
                      type: string
                      example: "Sample Category"
  /categories/{id}:
    get:
      summary: Get specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  name:
                    type: string
                    example: "Sample Category"
    put:
      summary: Update specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Category"
      responses:
        '200':
          description: Category updated successfully
    delete:
      summary: Delete specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "123"
      responses:
        '204':
          description: Category deleted successfully
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
  /passwords:
    post:
      summary: Create a new password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "user123"
                password:
                  type: string
                  example: "securepassword"
      responses:
        '201':
          description: Password created successfully
    get:
      summary: Get passwords filtered by user ID
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
            example: "user123"
      responses:
        '200':
          description: List of passwords
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "password123"
                    userId:
                      type: string
                      example: "user123"
  /passwords/{id}:
    get:
      summary: Get specific password by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "password123"
      responses:
        '200':
          description: Password details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "password123"
                  userId:
                    type: string
                    example: "user123"
    delete:
      summary: Delete specific password by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "password123"
      responses:
        '204':
          description: Password deleted successfully
  /points:
    post:
      summary: Create a new points entry
      responses:
        '201':
          description: Points entry created successfully
    get:
      summary: Get all points or filter by user ID and/or action ID
      responses:
        '200':
          description: List of points
  /points/{id}:
    get:
      summary: Get specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Points details
    put:
      summary: Update specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Points updated successfully
    delete:
      summary: Delete specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Points deleted successfully
  /rewards:
    post:
      summary: Create a new reward
      responses:
        '201':
          description: Reward created successfully
    get:
      summary: Get all rewards or filter by user ID
      responses:
        '200':
          description: List of rewards
  /rewards/{id}:
    get:
      summary: Get specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reward details
    put:
      summary: Update specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reward updated successfully
    delete:
      summary: Delete specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Reward deleted successfully
  /roles:
    post:
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Admin"
      responses:
        '201':
          description: Role created successfully
    get:
      summary: Get all roles
      responses:
        '200':
          description: List of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "role123"
                    name:
                      type: string
                      example: "Admin"
  /roles/{id}:
    get:
      summary: Get specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "role123"
      responses:
        '200':
          description: Role details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "role123"
                  name:
                    type: string
                    example: "Admin"
    put:
      summary: Update specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "role123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Role"
      responses:
        '200':
          description: Role updated successfully
    delete:
      summary: Delete specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "role123"
      responses:
        '204':
          description: Role deleted successfully
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "newuser@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '201':
          description: User created successfully
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "user123"
                    username:
                      type: string
                      example: "newuser@example.com"
  /users/{id}:
    get:
      summary: Get specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "user123"
                  username:
                    type: string
                    example: "newuser@example.com"
    put:
      summary: Update specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "updateduser@example.com"
      responses:
        '200':
          description: User updated successfully
    delete:
      summary: Delete specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      responses:
        '204':
          description: User deleted successfully