openapi: 3.0.0
info:
  title: OneUp API
  description: API contract for the OneUp project.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /actions:
    post:
      summary: Create a new action
      responses:
        '201':
          description: Action created successfully
    get:
      summary: Get all actions
      responses:
        '200':
          description: List of actions
  /actions/{id}:
    get:
      summary: Get specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Action details
    put:
      summary: Update specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Action updated successfully
    delete:
      summary: Delete specific action by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Action deleted successfully
  /auth/login:
    post:
      summary: Login
      responses:
        '200':
          description: Login successful
  /categories:
    post:
      summary: Create a new category
      responses:
        '201':
          description: Category created successfully
    get:
      summary: Get all categories
      responses:
        '200':
          description: List of categories
  /categories/{id}:
    get:
      summary: Get specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category details
    put:
      summary: Update specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category updated successfully
    delete:
      summary: Delete specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Category deleted successfully
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is healthy
  /passwords:
    post:
      summary: Create a new password
      responses:
        '201':
          description: Password created successfully
    get:
      summary: Get passwords filtered by user ID
      responses:
        '200':
          description: List of passwords
  /passwords/{id}:
    get:
      summary: Get specific password by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Password details
    delete:
      summary: Delete specific password by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Password deleted successfully
  /points:
    post:
      summary: Create a new points entry
      responses:
        '201':
          description: Points entry created successfully
    get:
      summary: Get all points or filter by user ID and/or action ID
      responses:
        '200':
          description: List of points
  /points/{id}:
    get:
      summary: Get specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Points details
    put:
      summary: Update specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Points updated successfully
    delete:
      summary: Delete specific points by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Points deleted successfully
  /rewards:
    post:
      summary: Create a new reward
      responses:
        '201':
          description: Reward created successfully
    get:
      summary: Get all rewards or filter by user ID
      responses:
        '200':
          description: List of rewards
  /rewards/{id}:
    get:
      summary: Get specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reward details
    put:
      summary: Update specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reward updated successfully
    delete:
      summary: Delete specific reward by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Reward deleted successfully
  /roles:
    post:
      summary: Create a new role
      responses:
        '201':
          description: Role created successfully
    get:
      summary: Get all roles
      responses:
        '200':
          description: List of roles
  /roles/{id}:
    get:
      summary: Get specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role details
    put:
      summary: Update specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role updated successfully
    delete:
      summary: Delete specific role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Role deleted successfully
  /users:
    post:
      summary: Create a new user
      responses:
        '201':
          description: User created successfully
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
  /users/{id}:
    get:
      summary: Get specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
    put:
      summary: Update specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User updated successfully
    delete:
      summary: Delete specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully